title: Keith Pitty
email: keith@keithpitty.com
description: >- 
  Keith Pitty's professional website.
baseurl: "" 
url: "https://keithpitty.com" 
twitter_username: keithpitty
github_username:  keithpitty

collections:
  achievements:
  testimonials:

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false
